version: "3"

services:
  instance-1:
    image: "sample-web-app"
    build:
      context: ./sample-web-app
      dockerfile: Dockerfile
  instance-2:
    image: "sample-web-app"
    build:
      context: ./sample-web-app
      dockerfile: Dockerfile
  instance-3:
    image: "sample-web-app"
    build:
      context: ./sample-web-app
      dockerfile: Dockerfile
