global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: instance1
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'instance-1:8080' ]

  - job_name: instance2
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'instance-2:8080' ]

  - job_name: instance3
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'instance-3:8080' ]
